### ISSUE TITLE
USER: Create a new project page

### ISSUE THREAD

**Issue by SterlingRed** [brucrew/brucrew#6]

**Comment by isaacmast** [comment]
I've gotten the page form to display and it accepts data and sends it to a dummy function in the model page. I tried copying the old code into the model function, but it didn't work. I think this might be because of the client name input field needing the list of client names that are already in the brucrew database. I have talked it over with @brucrew and I think he will be taking over the work for this part of the page. 

@brucrew, another thing for you to look into is that the datepicker in the Date Received field appears behind other HTML elements when it opens. I'm not sure how to get this to open in the foreground of the page, so you might want to look into that.

**Comment by brucrew** [comment]
Page completed by Jordan and Isaac.  Form and page structure by Isaac, client database interaction by Jordan
